services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    # Postgres was also considered (due to it being our preferred choice for the Registration DB),
    # however as it requires a plugin for WP to use it our current preference is to keep them separate.
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    ports:
      - 11434:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
  wp-cli:
    image: wordpress:cli
    user: "33:33"
    depends_on:
      - db
      - wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WP_CLI_CACHE_DIR=/tmp/wp-cli-cache
    volumes:
      - wp_data:/var/www/html/
      - ./import_data:/import_data
    working_dir: /var/www/html
    tty: true
    entrypoint: ["wp"]

volumes:
  db_data:
  wp_data:
